class FFArcana(object):
    deck = [
        {
            'value': 0,
            'card': '建筑神之塔',
            'position': '星极',
            'deity': '建筑与工艺之神比尔格',
            'attribute': '雷',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 1,
            'card': '河流神之瓶',
            'position': '星极',
            'deity': '河流与知识之神沙利亚克',
            'attribute': '水',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 2,
            'card': '世界树之干',
            'position': '星极',
            'deity': '大地与丰饶女神诺菲卡',
            'attribute': '土',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 3,
            'card': '放浪神之箭',
            'position': '星极',
            'deity': '海洋与航海女神利姆莱茵',
            'attribute': '风',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 4,
            'card': '太阳神之衡',
            'position': '星极',
            'deity': '太阳与审理女神阿泽玛',
            'attribute': '火',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 5,
            'card': '战争神之枪',
            'position': '星极',
            'deity': '冰河与战争女神哈罗妮',
            'attribute': '冰',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 6,
            'card': '建筑神之塔',
            'position': '灵极',
            'deity': '彗星与破坏之神拉尔戈',
            'attribute': '雷',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 7,
            'card': '河流神之瓶',
            'position': '灵极',
            'deity': '行星与命运女神妮美雅',
            'attribute': '水',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 8,
            'card': '世界树之干',
            'position': '灵极',
            'deity': '重力与光阴之神阿尔基克',
            'attribute': '土',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 9,
            'card': '放浪神之箭',
            'position': '灵极',
            'deity': '山岳与放浪之神奥修昂',
            'attribute': '风',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 10,
            'card': '太阳神之衡',
            'position': '灵极',
            'deity': '地底与商贸之神纳尔札尔',
            'attribute': '火',
            'meaning': '',
            'desc': '',
        },
        {
            'value': 11,
            'card': '战争神之枪',
            'position': '灵极',
            'deity': '双月与慈爱女神梅茵菲娜',
            'attribute': '冰',
            'meaning': '',
            'desc': '',
        },
    ]